title: Sophie Bass Frye Library Documentation
description: Digital preservation documentation for MOHAI's Sophie Bass Frye Library.
theme: just-the-docs

url: https://sophiebassfryelibrary.github.io/digi-pres-docs/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
